[project]
name = "service_controller"
version = "0.1.0"
description = "Add a short description here"
authors = ["yousif <yousifsayer@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
streamlit_service = "pixi run streamlit run app.py"

[dependencies]
streamlit = ">=1.32.2,<1.33"
python = ">=3.12.2,<3.13"
paramiko = ">=3.4.0,<3.5"

[pypi-dependencies]
extra-streamlit-components = "*"
st-pages = "*"
streamlit-extras = "*"
